[tool.ruff]
builtins = ["_"]
line-length = 88
target-version = "py310"
exclude = ["venv"]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "INP001",
    "W191",
    "D206",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "tab"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = 88

[tool.ruff.lint.pydocstyle]
convention = "google"